const DEFAULT_EVENTS = [
  {id:'goal',name:'Goal',on:true,score:true,color:'#dbf3e9'},
  {id:'assist',name:'Assist',on:true,color:'#e7f0fb'},
  {id:'shot',name:'Shot on goal',on:true,color:'#e1f2f5'},
  {id:'miss',name:'Missed shot',on:true,color:'#f8eee2'},
  {id:'block',name:'Blocked shot',on:true,color:'#f2eafa'},
  {id:'save',name:'Save',on:true,color:'#e9f5eb'},
  {id:'pass',name:'Completed pass',on:false,color:'#e9eff8'},
  {id:'takeaway',name:'Takeaway',on:false,color:'#f4f0df'},
  {id:'penalty',name:'Penalty',on:true,color:'#fae8e7'}
];
const NAV = [{id:'game',label:'Game',icon:'⏱'},{id:'roster',label:'Roster',icon:'👥'},{id:'events',label:'Events',icon:'⚙'},{id:'stats',label:'Stats',icon:'▤'},{id:'games',label:'Games',icon:'◷'}];
const fresh = () => ({team:'My Hockey Team',opponent:'',roster:[],events:structuredClone(DEFAULT_EVENTS),games:[],current:null,activeEvent:null,period:1});
let data;
try { data = JSON.parse(localStorage.getItem('shiftsheet-data')) || fresh(); } catch { data=fresh(); }
let currentView='game';
const save=()=>{localStorage.setItem('shiftsheet-data',JSON.stringify(data));render();};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeEvents=()=>data.events.filter(e=>e.on);
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function nav(){const html=NAV.map(n=>`<button class="${currentView===n.id?'active':''}" data-nav="${n.id}"><span class="navico">${n.icon}</span>${n.label}</button>`).join('');document.getElementById('topTabs').innerHTML=html;document.getElementById('bottomTabs').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{currentView=b.dataset.nav;render()});document.getElementById('teamLabel').textContent=data.team||'Your team';}
function gameView(){const root=document.getElementById('view-game');
  if(!data.current){root.innerHTML=`<div class="heading"><div><h1>Game day</h1><p>Track the action with a few quick taps.</p></div></div><div class="card setup-card"><h2>Start a game</h2><div class="field" style="margin-bottom:13px"><label>Team name</label><input id="teamInput" value="${esc(data.team)}" placeholder="e.g. North Stars U11"></div><div class="grid2"><div class="field"><label>Opponent</label><input id="oppInput" placeholder="Opponent name" value="${esc(data.opponent)}"></div><div class="field"><label>Game date</label><input id="dateInput" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="notice">Your roster and enabled event buttons are saved on this device. You can change which events appear in the Events tab.</div><button class="btn" id="startGame" style="width:100%;margin-top:16px">Start tracking</button></div>`;
    document.getElementById('startGame').onclick=()=>{data.team=document.getElementById('teamInput').value.trim()||'My Hockey Team';data.opponent=document.getElementById('oppInput').value.trim()||'Opponent';data.current={id:crypto.randomUUID(),date:document.getElementById('dateInput').value,opponent:data.opponent,started:new Date().toISOString(),events:[]};data.period=1;data.activeEvent=activeEvents()[0]?.id||null;save()};return;}
  const g=data.current;const teamGoals=g.events.filter(e=>e.side!=='opp'&&data.events.find(t=>t.id===e.type)?.score).length;const oppGoals=g.events.filter(e=>e.side==='opp'&&e.type==='goal').length;
  const roster=[...data.roster].sort((a,b)=>Number(a.number)-Number(b.number));
  root.innerHTML=`<div class="heading"><div><h1>${esc(g.opponent||'Game in progress')}</h1><p>${esc(g.date||'')} · ${data.period}${data.period===1?'st':data.period===2?'nd':data.period===3?'rd':'th'} period</p></div><button class="btn ghost small" id="periodBtn">Next period</button></div>
    <div class="scorecard"><div class="score-side"><strong>${esc(data.team)}</strong><b>${teamGoals}</b></div><div class="score-mid"><b>LIVE</b>VS</div><div class="score-side"><strong>${esc(g.opponent||'Opponent')}</strong><b>${oppGoals}</b></div></div>
    <div class="card"><div class="active-event"><div><span>EVENT TO LOG</span><br><b>${esc(data.events.find(e=>e.id===data.activeEvent)?.name||'Choose an event')}</b></div><span>${data.roster.length} players</span></div>
      <div class="event-pills">${activeEvents().map(e=>`<button class="event-pill ${data.activeEvent===e.id?'selected':''}" data-event="${esc(e.id)}">${esc(e.name)}</button>`).join('')||'<span class="muted">Enable events in the Events tab.</span>'}</div>
      <div class="subhead" style="margin-top:10px"><h2>Tap the player</h2><span class="muted">Jersey number · name</span></div>
      ${roster.length?`<div class="player-grid">${roster.map(p=>`<button class="player-tile" data-player="${esc(p.id)}"><span class="jersey">#${esc(p.number||'—')}</span><small>${esc(p.name)}</small></button>`).join('')}</div>`:`<div class="empty">Add your players in the Roster tab to start logging events.</div>`}
      <div class="row" style="margin-top:13px"><button class="btn ghost small" id="oppEvent">Log event for opponent</button><button class="btn danger small" id="endGame">End game</button></div>
    </div><div class="card"><div class="subhead" style="margin:0 0 7px"><h2>Recent events</h2><span class="muted">${g.events.length} logged</span></div><div class="recent">${recentRows(g.events.slice(-8).reverse())}</div></div>`;
  document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{data.activeEvent=b.dataset.event;save()});
  document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>logEvent(b.dataset.player,'team'));
  document.getElementById('periodBtn').onclick=()=>{data.period++;save();toast(`Period ${data.period}`)};
  document.getElementById('oppEvent').onclick=()=>{if(!data.activeEvent){toast('Choose an event first');return}logEvent(null,'opp')};
  document.getElementById('endGame').onclick=()=>{if(!confirm('End this game and save its stats?'))return;data.current.ended=new Date().toISOString();data.games.unshift(data.current);data.current=null;data.activeEvent=null;save();toast('Game saved')};
  document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.undo);g.events.splice(i,1);save();toast('Event removed')});
}
function recentRows(rows){if(!rows.length)return '<div class="empty">Your game events will show here.</div>';return rows.map(ev=>{const player=data.roster.find(p=>p.id===ev.player);return `<div class="event-row"><span class="event-time">P${ev.period}</span><div><div class="event-name">${esc(ev.eventLabel||data.events.find(e=>e.id===ev.type)?.name||ev.type)}${ev.side==='opp'?' · Opponent':''}</div><div class="event-detail">${ev.player?`#${esc(player?.number||'')} ${esc(player?.name||'Removed player')}`:ev.side==='opp'?'Opponent':'Team'} · ${new Date(ev.at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div></div><button class="iconbtn" data-undo="${data.current?data.current.events.indexOf(ev):-1}" title="Undo">Undo</button></div>`}).join('')}
function logEvent(player,side){if(!data.activeEvent){toast('Choose an event first');return}const type=data.events.find(e=>e.id===data.activeEvent);data.current.events.push({id:crypto.randomUUID(),type:data.activeEvent,eventLabel:type?.name||data.activeEvent,player:side==='team'?player:null,side,period:data.period,at:new Date().toISOString()});save();const p=data.roster.find(x=>x.id===player);toast(`${type?.name||'Event'} logged${p?' · #'+p.number:''}`)}
function rosterView(){const root=document.getElementById('view-roster');root.innerHTML=`<div class="heading"><div><h1>Roster</h1><p>Use jersey numbers so you can find players quickly during play.</p></div></div><div class="card"><h2>Add a player</h2><div class="grid2"><div class="field"><label>Jersey number</label><input id="newNumber" inputmode="numeric" placeholder="e.g. 12"></div><div class="field"><label>Player name</label><input id="newName" placeholder="First name"></div></div><button class="btn" id="addPlayer" style="margin-top:12px;width:100%">Add to roster</button></div><div class="card"><div class="subhead" style="margin:0 0 7px"><h2>Players</h2><span class="muted">${data.roster.length} total</span></div>${data.roster.length?data.roster.slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<div class="roster-row"><span class="jersey">#${esc(p.number||'—')}</span><span class="roster-name">${esc(p.name)}</span><button class="iconbtn" data-remove-player="${esc(p.id)}">Remove</button></div>`).join(''):'<div class="empty">No players added yet.</div>'}<div class="notice">Only add the names and numbers needed to keep your own team’s scorebook. This version stores information on this device.</div></div>`;
  document.getElementById('addPlayer').onclick=()=>{const name=document.getElementById('newName').value.trim();const number=document.getElementById('newNumber').value.trim();if(!name){toast('Enter a player name');return}data.roster.push({id:crypto.randomUUID(),name,number});save();toast('Player added')};document.querySelectorAll('[data-remove-player]').forEach(b=>b.onclick=()=>{data.roster=data.roster.filter(p=>p.id!==b.dataset.removePlayer);save()});}
function eventsView(){const root=document.getElementById('view-events');root.innerHTML=`<div class="heading"><div><h1>Game events</h1><p>Choose exactly which buttons show up on game day.</p></div></div><div class="card"><h2>Enabled events</h2>${data.events.map(e=>`<div class="config-row"><span class="config-name">${esc(e.name)}</span>${e.score?'<span class="muted">counts as goal</span>':''}<input class="toggle" type="checkbox" data-toggle-event="${esc(e.id)}" ${e.on?'checked':''} aria-label="Enable ${esc(e.name)}">${e.id.startsWith('custom-')?`<button class="iconbtn" data-delete-event="${esc(e.id)}">Delete</button>`:''}</div>`).join('')}<div class="notice">Turn off events your team doesn’t track. Changes are saved on this device and apply to the game screen immediately.</div></div><div class="card"><h2>Create a custom event</h2><div class="field"><label>Event name</label><input id="customEventName" placeholder="e.g. Successful zone exit"></div><button class="btn secondary" id="addEvent" style="margin-top:11px;width:100%">Add custom event</button><div class="notice">Custom events are counted per player, just like built-in events. You can enable or disable them whenever you like.</div></div><div class="card"><h2>Team settings</h2><div class="field"><label>Team name</label><input id="editTeamName" value="${esc(data.team)}"></div><button class="btn ghost" id="saveTeamName" style="margin-top:11px;width:100%">Save team name</button></div>`;
  document.querySelectorAll('[data-toggle-event]').forEach(c=>c.onchange=()=>{const e=data.events.find(e=>e.id===c.dataset.toggleEvent);e.on=c.checked;save()});document.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>{const e=data.events.find(e=>e.id===b.dataset.deleteEvent);if(confirm(`Remove “${e.name}” from the event list? Previously logged entries stay in game history.`)){data.events=data.events.filter(item=>item.id!==e.id);if(data.activeEvent===e.id)data.activeEvent=activeEvents()[0]?.id||null;save()}});document.getElementById('addEvent').onclick=()=>{const name=document.getElementById('customEventName').value.trim();if(!name){toast('Type an event name');return}data.events.push({id:'custom-'+crypto.randomUUID(),name,on:true,color:'#edf2f4'});save();toast('Custom event added')};document.getElementById('saveTeamName').onclick=()=>{data.team=document.getElementById('editTeamName').value.trim()||'My Hockey Team';save();toast('Team name saved')};}
function statRows(games){const rows={};for(const g of games)for(const ev of g.events){if(ev.side==='opp'||!ev.player)continue;const p=data.roster.find(p=>p.id===ev.player);const key=ev.player;if(!rows[key])rows[key]={player:p?.name||'Removed player',number:p?.number||'',counts:{}};rows[key].counts[ev.type]=(rows[key].counts[ev.type]||0)+1}return rows;}
function statsView(){const root=document.getElementById('view-stats');const games=[...data.games,...(data.current?[data.current]:[])];const rows=statRows(games);const used=new Set(games.flatMap(g=>g.events.map(e=>e.type)));const byId=new Map(data.events.map(e=>[e.id,e]));for(const g of games)for(const ev of g.events)if(!byId.has(ev.type))byId.set(ev.type,{id:ev.type,name:ev.eventLabel||ev.type});const chosen=[...used].map(id=>byId.get(id));const count=ev=>Object.values(rows).reduce((n,r)=>n+(r.counts[ev.id]||0),0);root.innerHTML=`<div class="heading"><div><h1>Season stats</h1><p>Player totals from games recorded on this device.</p></div><div class="export-actions"><button class="btn secondary small" id="exportPdf">Export PDF</button><button class="btn secondary small" id="exportTotals">Player totals CSV</button><button class="btn ghost small" id="exportEvents">Event log CSV</button></div></div><div class="card"><h2>${games.length} game${games.length===1?'':'s'} · ${data.roster.length} players</h2>${data.roster.length&&chosen.length?`<div class="scroll-x"><table class="stats-table"><thead><tr><th>Player</th>${chosen.map(e=>`<th>${esc(e.name)}</th>`).join('')}</tr></thead><tbody>${data.roster.slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<tr><td><b>#${esc(p.number||'—')}</b> ${esc(p.name)}</td>${chosen.map(e=>`<td>${rows[p.id]?.counts[e.id]||0}</td>`).join('')}</tr>`).join('')}<tr><td><b>Team total</b></td>${chosen.map(e=>`<td><b>${count(e)}</b></td>`).join('')}</tr></tbody></table></div>`:'<div class="empty">Log a game with player events to see the season summary.</div>'}<div class="notice">Export a printable PDF report, player totals for a spreadsheet, or a detailed event log. CSV files open in Excel, Numbers, and Google Sheets.</div></div>`;document.getElementById('exportPdf').onclick=()=>exportPdf(games,chosen,rows);document.getElementById('exportTotals').onclick=()=>exportTotalsCsv(chosen,rows);document.getElementById('exportEvents').onclick=()=>exportCsv(games);}
function gamesView(){const root=document.getElementById('view-games');root.innerHTML=`<div class="heading"><div><h1>Game history</h1><p>Your saved games and the stats you can share.</p></div></div><div class="card">${data.games.length?data.games.map(g=>{const goals=g.events.filter(e=>data.events.find(t=>t.id===e.type)?.score&&e.side!=='opp').length;const opp=g.events.filter(e=>e.type==='goal'&&e.side==='opp').length;return `<div class="game-row"><div class="game-title">${esc(g.opponent||'Game')}<div class="muted">${esc(g.date||'')} · ${g.events.length} events</div></div><b>${goals}–${opp}</b><button class="iconbtn" data-share-game="${esc(g.id)}">Share</button><button class="iconbtn" data-delete-game="${esc(g.id)}">Delete</button></div>`}).join(''):'<div class="empty">Finished games will be saved here.</div>'}<div class="notice">Use Share to copy a short game summary, or export CSV from Season Stats for the full event list.</div></div>`;
  document.querySelectorAll('[data-share-game]').forEach(b=>b.onclick=()=>shareGame(data.games.find(g=>g.id===b.dataset.shareGame)));document.querySelectorAll('[data-delete-game]').forEach(b=>b.onclick=()=>{if(confirm('Delete this saved game?')){data.games=data.games.filter(g=>g.id!==b.dataset.deleteGame);save()}})}
function shareGame(g){if(!g)return;const goals=g.events.filter(e=>data.events.find(t=>t.id===e.type)?.score&&e.side!=='opp').length;const opp=g.events.filter(e=>e.type==='goal'&&e.side==='opp').length;const totals={};for(const ev of g.events){if(ev.side==='opp'||!ev.player)continue;const p=data.roster.find(p=>p.id===ev.player);const name=p?`#${p.number||'—'} ${p.name}`:'Player';const eventName=ev.eventLabel||data.events.find(e=>e.id===ev.type)?.name||ev.type;totals[name]??={};totals[name][eventName]=(totals[name][eventName]||0)+1}const details=Object.entries(totals).map(([p,counts])=>`${p}: ${Object.entries(counts).map(([label,n])=>`${label} ${n}`).join(', ')}`).join('\n');const msg=`${data.team} vs ${g.opponent} · ${g.date}\nTracked score: ${goals}–${opp}\n${details||'No player events recorded.'}\n\nTracked with ShiftSheet.`;if(navigator.share)navigator.share({title:'Hockey game summary',text:msg}).catch(()=>{});else navigator.clipboard?.writeText(msg).then(()=>toast('Game summary copied')).catch(()=>toast('Use Export CSV from Season Stats to share the full scorebook.'))}
function downloadCsv(lines,filename){const csv=lines.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Spreadsheet file exported')}
function exportCsv(games){const lines=[['Date','Opponent','Period','Event','Side','Jersey','Player','Time']];for(const g of games)for(const ev of g.events){const p=data.roster.find(p=>p.id===ev.player);lines.push([g.date,g.opponent,ev.period,ev.eventLabel||data.events.find(e=>e.id===ev.type)?.name||ev.type,ev.side,p?.number||'',p?.name||'',ev.at])}downloadCsv(lines,'shiftsheet-event-log.csv')}
function exportTotalsCsv(events,rows){const lines=[['Jersey','Player',...events.map(e=>e.name)]];for(const p of data.roster.slice().sort((a,b)=>Number(a.number)-Number(b.number)))lines.push([p.number||'',p.name,...events.map(e=>rows[p.id]?.counts[e.id]||0)]);lines.push(['','Team total',...events.map(e=>Object.values(rows).reduce((n,r)=>n+(r.counts[e.id]||0),0))]);downloadCsv(lines,'shiftsheet-player-totals.csv')}
function exportPdf(games,events,rows){const report=document.getElementById('printReport');const sorted=data.roster.slice().sort((a,b)=>Number(a.number)-Number(b.number));const totalRow=events.map(e=>Object.values(rows).reduce((n,r)=>n+(r.counts[e.id]||0),0));const totalTable=events.length?`<table><thead><tr><th>Player</th>${events.map(e=>`<th>${esc(e.name)}</th>`).join('')}</tr></thead><tbody>${sorted.map(p=>`<tr><td>#${esc(p.number||'—')} ${esc(p.name)}</td>${events.map(e=>`<td>${rows[p.id]?.counts[e.id]||0}</td>`).join('')}</tr>`).join('')}<tr><th>Team total</th>${totalRow.map(n=>`<th>${n}</th>`).join('')}</tr></tbody></table>`:'<p>No stats recorded yet.</p>';const gameRows=games.map(g=>{const gf=g.events.filter(e=>data.events.find(t=>t.id===e.type)?.score&&e.side!=='opp').length;const ga=g.events.filter(e=>e.type==='goal'&&e.side==='opp').length;return `<tr><td>${esc(g.date||'')}</td><td>${esc(g.opponent||'')}</td><td>${gf}–${ga}</td><td>${g.events.length}</td></tr>`}).join('');const logRows=games.flatMap(g=>g.events.map(ev=>{const p=data.roster.find(p=>p.id===ev.player);return `<tr><td>${esc(g.date||'')}</td><td>${esc(g.opponent||'')}</td><td>${ev.period}</td><td>${esc(ev.eventLabel||data.events.find(e=>e.id===ev.type)?.name||ev.type)}</td><td>${ev.side==='opp'?'Opponent':'Team'}</td><td>${ev.player?`#${esc(p?.number||'')} ${esc(p?.name||'Removed player')}`:''}</td></tr>`})).join('');report.innerHTML=`<h1>${esc(data.team)} · Season stats</h1><p class="report-meta">${games.length} games · ${sorted.length} players · Created ${new Date().toLocaleDateString()}</p><h2>Player totals</h2>${totalTable}<h2>Game results</h2><table><thead><tr><th>Date</th><th>Opponent</th><th>Tracked score</th><th>Events logged</th></tr></thead><tbody>${gameRows||'<tr><td colspan="4">No games recorded</td></tr>'}</tbody></table><h2>Event log</h2><table><thead><tr><th>Date</th><th>Opponent</th><th>Period</th><th>Event</th><th>Side</th><th>Player</th></tr></thead><tbody>${logRows||'<tr><td colspan="6">No events recorded</td></tr>'}</tbody></table><p class="report-foot">Generated by ShiftSheet. Stats are manually recorded and may not include every game event.</p>`;window.print()}
function render(){nav();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${currentView}`));gameView();if(currentView==='roster')rosterView();if(currentView==='events')eventsView();if(currentView==='stats')statsView();if(currentView==='games')gamesView()}
if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
